Repository bullhorn/novo-elements, pull requests merged in 2018-08, with the labels that each got.

#773 Change to add dept and title fields to the internal picker
  src/platform/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
Labels: merge please

#756 fix(Render): remove extra whitespace from address rendering
  src/platform/elements/value/Render.ts
Labels: bug, needs discussion

#784 fix(Picker): Make picker results dynamic height so they fit on screen
  src/platform/elements/chips/Chips.scss
  src/platform/elements/picker/Picker.scss
Labels: merge please

#793 feat(NovoRowChipsElement): Add extension of NovoChipsElement, NovoRowChipsElements.
  src/app/pages/elements/chips/ChipsDemo.ts
  src/app/pages/elements/chips/templates/RowChipsDemo.html
  src/platform/elements/chips/Chips.module.ts
  src/platform/elements/chips/Chips.scss
  src/platform/elements/chips/RowChips.spec.ts
  src/platform/elements/chips/RowChips.ts
  src/platform/elements/form/ControlTemplates.ts
  src/platform/utils/form-utils/FormUtils.ts
Labels: feature
