Repository bullhorn/novo-elements, pull requests merged in 2022-04, with the labels that each got.

#1290 fix(NovoDataTable): making pagination marker background color dynamic
  projects/novo-elements/src/elements/data-table/data-table.component.scss
Labels: bug

#1293 fix(Theme): text colors are now darker
  .gitignore
  package-lock.json
  projects/novo-elements/src/elements/button/styles/button-other.scss
  projects/novo-elements/src/elements/calendar/calendar.component.scss
  projects/novo-elements/src/elements/calendar/month-view/month-view.component.scss
  projects/novo-elements/src/elements/common/option/option.component.scss
  projects/novo-elements/src/elements/common/typography/text.mixins.scss
  projects/novo-elements/src/elements/form/ControlGroup.scss
  projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.scss
  projects/novo-elements/src/novo-elements.scss
  projects/novo-elements/src/styles/themes/dark.scss
  projects/novo-elements/src/styles/themes/light.scss
  projects/novo-elements/src/styles/typography.scss
Labels: design

#1278 feat(picker): Adjusting how picker overlay appears for row chips.
  projects/novo-elements/src/elements/chips/RowChips.ts
Labels: feature, merge please
